#!/usr/bin/env bash

SERVICE_NAME="actions-service"
TAG=${TAG:-$SERVICE_NAME}
VERSION=${VERSION:-""}
REGISTRY=${REGISTRY:-"gcf-artifacts"}
REGION=${REGION:-""}
PROJECT=${PROJECT:-""}

while [ $# -gt 0 ]; do
   if [[ $1 == *"--"* ]]; then
        PARAM="${1/--/}"
        PARAM="$(echo $PARAM | tr 'a-z' 'A-Z')"
        if [[ -z $2 ]] || [[ $2 == *"--"* ]] || [[ $2 == "" ]]; then
          declare $PARAM=true
        else
          declare $PARAM="$2"
        fi
   fi
  shift
done

[[ -z $REGION ]] && { echo "Missing required flag [region]. Exiting."; exit 1;}

if [[ -z $VERSION ]]; then
  PACKAGE_JSON_VERSION="$(jq -r '.version' package.json)"
  echo "[ $(date +%T) ] Missing flag [version]. Using version from package.json ($PACKAGE_JSON_VERSION)."
  VERSION=$PACKAGE_JSON_VERSION
fi

if [[ -z $PROJECT ]]; then
  GCLOUD_PROJECT="$(gcloud config get core/project)"
  if [[ -z $GCLOUD_PROJECT ]]; then
    echo "Missing flag [project] and no gcloud default project set. Exiting."
    exit 1
  else
    echo "[ $(date +%T) ] Missing flag [project]. Using gcloud default ($GCLOUD_PROJECT)."
    PROJECT=$GCLOUD_PROJECT
  fi
fi

echo "[ $(date +%T) ] Building container $TAG:$VERSION."

docker build . -t $TAG:$VERSION --platform linux/amd64
docker tag $TAG:$VERSION "$REGION-docker.pkg.dev/$PROJECT/$REGISTRY/$TAG:$VERSION"

echo "[ $(date +%T) ] Built container $TAG:$VERSION."

TMP=$(mktemp)
jq --arg v "$VERSION" '.version = $v' package.json > "$TMP" && mv "$TMP" package.json
echo "[ $(date +%T) ] Updated package.json version ($VERSION)."
