#!/usr/bin/env bash

ROOT="$(pwd)"
ACTIONS_SERVICE_VERSION=${ACTIONS_SERVICE_VERSION:-""}
GRAPHQL_SERVICE_VERSION=${GRAPHQL_SERVICE_VERSION:-""}
REDIRECTIONS_SERVICE_VERSION=${REDIRECTIONS_SERVICE_VERSION:-""}
RULES_ENGINE_SERVICE_VERSION=${RULES_ENGINE_SERVICE_VERSION:-""}

if [ $# -gt 0 ]; then
  while [ $# -gt 0 ]; do
     if [[ $1 == *"--"* ]]; then
          PARAM="${1/--/}"
          PARAM="$(echo $PARAM | tr 'a-z' 'A-Z')"
          PARAM="$(echo $PARAM | tr '-' '_')"
          declare $PARAM="$2"
     fi
    shift
  done
fi

if [[ -z $ACTIONS_SERVICE_VERSION ]]; then
  PACKAGE_JSON_VERSION="$(jq -r '.version' ./services/actions/package.json)"
  echo "[ $(date +%T) ] Missing flag [actions-service-version]. Using version from package.json. ($PACKAGE_JSON_VERSION)"
  ACTIONS_SERVICE_VERSION=$PACKAGE_JSON_VERSION
fi

if [[ -z $GRAPHQL_SERVICE_VERSION ]]; then
  PACKAGE_JSON_VERSION="$(jq -r '.version' ./services/graphql/package.json)"
  echo "[ $(date +%T) ] Missing flag [graphql-service-version]. Using version from package.json. ($PACKAGE_JSON_VERSION)"
  GRAPHQL_SERVICE_VERSION=$PACKAGE_JSON_VERSION
fi

if [[ -z $REDIRECTIONS_SERVICE_VERSION ]]; then
  PACKAGE_JSON_VERSION="$(jq -r '.version' ./services/redirections/package.json)"
  echo "[ $(date +%T) ] Missing flag [redirections-service-version]. Using version from package.json. ($PACKAGE_JSON_VERSION)"
  REDIRECTIONS_SERVICE_VERSION=$PACKAGE_JSON_VERSION
fi

if [[ -z $RULES_ENGINE_SERVICE_VERSION ]]; then
  PACKAGE_JSON_VERSION="$(jq -r '.version' ./services/rules-engine/package.json)"
  echo "[ $(date +%T) ] Missing flag [rules-engine-service-version]. Using version from package.json. ($PACKAGE_JSON_VERSION)"
  RULES_ENGINE_SERVICE_VERSION=$PACKAGE_JSON_VERSION
fi

echo "[ $(date +%T) ] Beginning destroy."

cd ./terraform

TF_VAR_actions_service_version=$ACTIONS_SERVICE_VERSION \
TF_VAR_redirections_service_version=$REDIRECTIONS_SERVICE_VERSION \
TF_VAR_rules_engine_service_version=$RULES_ENGINE_SERVICE_VERSION \
TF_VAR_graphql_service_version=$GRAPHQL_SERVICE_VERSION \
terraform destroy

echo "[ $(date +%T) ] Completed destroy."

cd $ROOT
