#!/usr/bin/env bash

ROOT="$(pwd)"
ACTIONS_SERVICE_VERSION="$(jq -r '.version' ./services/actions/package.json)"
GRAPHQL_SERVICE_VERSION="$(jq -r '.version' ./services/graphql/package.json)"
REDIRECTIONS_SERVICE_VERSION="$(jq -r '.version' ./services/redirections/package.json)"
RULES_SERVICE_VERSION="$(jq -r '.version' ./services/rules/package.json)"

VERSIONS=$(cat << END
Service|Version
Actions Service|$ACTIONS_SERVICE_VERSION
GraphQL Service|$GRAPHQL_SERVICE_VERSION
Redirections Service|$REDIRECTIONS_SERVICE_VERSION
Rules Service|$RULES_SERVICE_VERSION
END
)

echo "Redirector POC"
echo ""
echo "$VERSIONS" | column -t -s'|'

cd ./terraform

TF_VAR_actions_service_version=$ACTIONS_SERVICE_VERSION \
TF_VAR_redirections_service_version=$REDIRECTIONS_SERVICE_VERSION \
TF_VAR_rules_service_version=$RULES_SERVICE_VERSION \
TF_VAR_graphql_service_version=$GRAPHQL_SERVICE_VERSION \
terraform "$@"

cd $ROOT
